<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InsuranceCompany;

class InsuranceCompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies = [
            [
                'name_ar' => 'شركة التأمين الطبي الشامل',
                'name_en' => 'Comprehensive Medical Insurance Company',
                'code' => 'CMIC',
                'commercial_registration' => '1010123456',
                'tax_number' => '300123456789003',
                'phone' => '+966112345678',
                'email' => 'info@cmic.com.sa',
                'website' => 'https://www.cmic.com.sa',
                'address_ar' => 'الرياض، حي الملز، شارع الملك فهد',
                'address_en' => 'Riyadh, Al Malaz District, King Fahd Road',
                'default_coverage_percentage' => 80.00,
                'max_coverage_amount' => 100000.00,
                'deductible_amount' => 500.00,
                'covered_services' => ['consultation', 'lab_test', 'radiology', 'surgery', 'medication'],
                'excluded_services' => ['cosmetic', 'dental_cosmetic'],
                'payment_terms_days' => 30,
                'discount_percentage' => 5.00,
                'payment_method' => 'bank_transfer',
                'bank_name' => 'البنك الأهلي السعودي',
                'bank_account_number' => '123456789012',
                'iban' => 'SA1234567890123456789012',
                'swift_code' => 'NCBKSARI',
                'contract_start_date' => '2024-01-01',
                'contract_end_date' => '2025-12-31',
                'contract_status' => 'active',
                'is_active' => true,
                'notes' => 'شركة تأمين رائدة في المملكة العربية السعودية',
            ],
            [
                'name_ar' => 'شركة الحماية للتأمين الصحي',
                'name_en' => 'Al Himaya Health Insurance Company',
                'code' => 'AHIC',
                'commercial_registration' => '1010234567',
                'tax_number' => '300234567890003',
                'phone' => '+966112345679',
                'email' => 'contact@ahic.com.sa',
                'website' => 'https://www.ahic.com.sa',
                'address_ar' => 'جدة، حي الروضة، طريق الملك عبدالعزيز',
                'address_en' => 'Jeddah, Al Rawda District, King Abdulaziz Road',
                'default_coverage_percentage' => 75.00,
                'max_coverage_amount' => 75000.00,
                'deductible_amount' => 300.00,
                'covered_services' => ['consultation', 'lab_test', 'radiology', 'emergency'],
                'excluded_services' => ['cosmetic', 'fertility_treatment'],
                'payment_terms_days' => 45,
                'discount_percentage' => 3.00,
                'payment_method' => 'bank_transfer',
                'bank_name' => 'بنك الراجحي',
                'bank_account_number' => '234567890123',
                'iban' => 'SA2345678901234567890123',
                'swift_code' => 'RJHISARI',
                'contract_start_date' => '2024-06-01',
                'contract_end_date' => '2025-05-31',
                'contract_status' => 'active',
                'is_active' => true,
                'notes' => 'تركز على التأمين الصحي للعائلات',
            ],
            [
                'name_ar' => 'شركة الأمان للتأمين التعاوني',
                'name_en' => 'Al Amaan Cooperative Insurance Company',
                'code' => 'ACIC',
                'commercial_registration' => '1010345678',
                'tax_number' => '300345678901003',
                'phone' => '+966112345680',
                'email' => 'info@acic.com.sa',
                'website' => 'https://www.acic.com.sa',
                'address_ar' => 'الدمام، حي الفيصلية، شارع الأمير محمد بن فهد',
                'address_en' => 'Dammam, Al Faisaliyah District, Prince Mohammed bin Fahd Street',
                'default_coverage_percentage' => 85.00,
                'max_coverage_amount' => 150000.00,
                'deductible_amount' => 1000.00,
                'covered_services' => ['consultation', 'lab_test', 'radiology', 'surgery', 'medication', 'dental'],
                'excluded_services' => ['cosmetic'],
                'payment_terms_days' => 60,
                'discount_percentage' => 7.00,
                'payment_method' => 'bank_transfer',
                'bank_name' => 'بنك سامبا',
                'bank_account_number' => '345678901234',
                'iban' => 'SA3456789012345678901234',
                'swift_code' => 'SAMBSARI',
                'contract_start_date' => '2024-03-01',
                'contract_end_date' => '2026-02-28',
                'contract_status' => 'active',
                'is_active' => true,
                'notes' => 'تغطية شاملة للخدمات الطبية والأسنان',
            ],
            [
                'name_ar' => 'شركة الوطنية للتأمين الصحي',
                'name_en' => 'National Health Insurance Company',
                'code' => 'NHIC',
                'commercial_registration' => '1010456789',
                'tax_number' => '300456789012003',
                'phone' => '+966112345681',
                'email' => 'support@nhic.com.sa',
                'website' => 'https://www.nhic.com.sa',
                'address_ar' => 'الرياض، حي العليا، طريق الملك فهد',
                'address_en' => 'Riyadh, Al Olaya District, King Fahd Road',
                'default_coverage_percentage' => 70.00,
                'max_coverage_amount' => 50000.00,
                'deductible_amount' => 200.00,
                'covered_services' => ['consultation', 'lab_test', 'emergency'],
                'excluded_services' => ['cosmetic', 'dental', 'fertility_treatment'],
                'payment_terms_days' => 30,
                'discount_percentage' => 2.00,
                'payment_method' => 'check',
                'bank_name' => 'البنك السعودي للاستثمار',
                'bank_account_number' => '456789012345',
                'iban' => 'SA4567890123456789012345',
                'swift_code' => 'SIBCSARI',
                'contract_start_date' => '2024-01-01',
                'contract_end_date' => '2024-12-31',
                'contract_status' => 'active',
                'is_active' => true,
                'notes' => 'تأمين أساسي للخدمات الطبية الضرورية',
            ],
            [
                'name_ar' => 'شركة المتحدة للتأمين الطبي',
                'name_en' => 'United Medical Insurance Company',
                'code' => 'UMIC',
                'commercial_registration' => '1010567890',
                'tax_number' => '300567890123003',
                'phone' => '+966112345682',
                'email' => 'info@umic.com.sa',
                'website' => 'https://www.umic.com.sa',
                'address_ar' => 'مكة المكرمة، حي العزيزية، شارع إبراهيم الخليل',
                'address_en' => 'Makkah, Al Aziziyah District, Ibrahim Al Khalil Street',
                'default_coverage_percentage' => 90.00,
                'max_coverage_amount' => 200000.00,
                'deductible_amount' => 1500.00,
                'covered_services' => ['consultation', 'lab_test', 'radiology', 'surgery', 'medication', 'dental', 'emergency'],
                'excluded_services' => ['cosmetic'],
                'payment_terms_days' => 90,
                'discount_percentage' => 10.00,
                'payment_method' => 'bank_transfer',
                'bank_name' => 'بنك البلاد',
                'bank_account_number' => '567890123456',
                'iban' => 'SA5678901234567890123456',
                'swift_code' => 'ALBISARI',
                'contract_start_date' => '2024-07-01',
                'contract_end_date' => '2025-06-30',
                'contract_status' => 'active',
                'is_active' => true,
                'notes' => 'تغطية متميزة للخدمات الطبية الشاملة',
            ],
            [
                'name_ar' => 'شركة الخليج للتأمين الصحي',
                'name_en' => 'Gulf Health Insurance Company',
                'code' => 'GHIC',
                'commercial_registration' => '1010678901',
                'tax_number' => '300678901234003',
                'phone' => '+966112345683',
                'email' => 'contact@ghic.com.sa',
                'website' => 'https://www.ghic.com.sa',
                'address_ar' => 'الخبر، حي الثقبة، طريق الملك فهد',
                'address_en' => 'Al Khobar, Al Thuqbah District, King Fahd Road',
                'default_coverage_percentage' => 65.00,
                'max_coverage_amount' => 40000.00,
                'deductible_amount' => 250.00,
                'covered_services' => ['consultation', 'lab_test', 'medication'],
                'excluded_services' => ['cosmetic', 'dental', 'surgery', 'radiology'],
                'payment_terms_days' => 30,
                'discount_percentage' => 0.00,
                'payment_method' => 'online',
                'bank_name' => 'بنك الخليج',
                'bank_account_number' => '678901234567',
                'iban' => 'SA6789012345678901234567',
                'swift_code' => 'GULFSARI',
                'contract_start_date' => '2024-01-01',
                'contract_end_date' => '2025-01-15',
                'contract_status' => 'suspended',
                'is_active' => false,
                'notes' => 'تأمين محدود - معلق مؤقتاً لمراجعة الشروط',
            ]
        ];

        foreach ($companies as $company) {
            InsuranceCompany::create($company);
        }

        $this->command->info('تم إنشاء ' . count($companies) . ' شركة تأمين بنجاح');
    }
}