<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SurgicalProcedure;

class SurgicalProcedureSeeder extends Seeder
{
    public function run(): void
    {
        $procedures = [
            // General Surgery
            [
                'code' => 'GS001',
                'name' => 'Appendectomy',
                'name_ar' => 'استئصال الزائدة الدودية',
                'description' => 'Surgical removal of the appendix',
                'description_ar' => 'الاستئصال الجراحي للزائدة الدودية',
                'category' => 'general',
                'specialty' => 'general_surgery',
                'complexity' => 'moderate',
                'urgency_level' => 'urgent',
                'estimated_duration' => 60,
                'min_duration' => 45,
                'max_duration' => 90,
                'base_cost' => 5000.00,
                'surgeon_fee' => 2000.00,
                'anesthesia_fee' => 800.00,
                'facility_fee' => 1200.00,
                'required_equipment' => ['laparoscope', 'electrocautery', 'suction'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'scrub_nurse'],
                'pre_operative_requirements' => ['blood_work', 'imaging', 'consent'],
                'post_operative_care' => ['pain_management', 'wound_care', 'diet_progression'],
                'requires_icu' => false,
                'requires_blood_bank' => false,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            [
                'code' => 'GS002',
                'name' => 'Cholecystectomy',
                'name_ar' => 'استئصال المرارة',
                'description' => 'Surgical removal of the gallbladder',
                'description_ar' => 'الاستئصال الجراحي للمرارة',
                'category' => 'general',
                'specialty' => 'general_surgery',
                'complexity' => 'moderate',
                'urgency_level' => 'elective',
                'estimated_duration' => 90,
                'min_duration' => 60,
                'max_duration' => 120,
                'base_cost' => 8000.00,
                'surgeon_fee' => 3000.00,
                'anesthesia_fee' => 1000.00,
                'facility_fee' => 1500.00,
                'required_equipment' => ['laparoscope', 'electrocautery', 'clips'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'scrub_nurse'],
                'pre_operative_requirements' => ['blood_work', 'imaging', 'consent', 'cardiac_clearance'],
                'post_operative_care' => ['pain_management', 'wound_care', 'diet_progression'],
                'requires_icu' => false,
                'requires_blood_bank' => false,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            
            // Cardiac Surgery
            [
                'code' => 'CS001',
                'name' => 'Coronary Artery Bypass',
                'name_ar' => 'جراحة تحويل الشرايين التاجية',
                'description' => 'Surgical procedure to improve blood flow to the heart',
                'description_ar' => 'إجراء جراحي لتحسين تدفق الدم إلى القلب',
                'category' => 'cardiac',
                'specialty' => 'cardiac_surgery',
                'complexity' => 'complex',
                'urgency_level' => 'urgent',
                'estimated_duration' => 240,
                'min_duration' => 180,
                'max_duration' => 360,
                'base_cost' => 50000.00,
                'surgeon_fee' => 20000.00,
                'anesthesia_fee' => 5000.00,
                'facility_fee' => 10000.00,
                'required_equipment' => ['heart_lung_machine', 'cardiac_monitors', 'defibrillator'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'perfusionist', 'scrub_nurse', 'circulating_nurse'],
                'pre_operative_requirements' => ['cardiac_catheterization', 'echo', 'blood_work', 'consent'],
                'post_operative_care' => ['icu_monitoring', 'ventilator_support', 'cardiac_monitoring'],
                'requires_icu' => true,
                'requires_blood_bank' => true,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            
            // Orthopedic Surgery
            [
                'code' => 'OS001',
                'name' => 'Total Knee Replacement',
                'name_ar' => 'استبدال الركبة الكامل',
                'description' => 'Complete replacement of knee joint',
                'description_ar' => 'الاستبدال الكامل لمفصل الركبة',
                'category' => 'orthopedic',
                'specialty' => 'orthopedic_surgery',
                'complexity' => 'major',
                'urgency_level' => 'elective',
                'estimated_duration' => 120,
                'min_duration' => 90,
                'max_duration' => 180,
                'base_cost' => 25000.00,
                'surgeon_fee' => 10000.00,
                'anesthesia_fee' => 2000.00,
                'facility_fee' => 5000.00,
                'required_equipment' => ['orthopedic_instruments', 'prosthesis', 'cement'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'scrub_nurse'],
                'pre_operative_requirements' => ['xray', 'blood_work', 'consent', 'physical_therapy_eval'],
                'post_operative_care' => ['pain_management', 'physical_therapy', 'wound_care'],
                'requires_icu' => false,
                'requires_blood_bank' => true,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            
            // Neurosurgery
            [
                'code' => 'NS001',
                'name' => 'Craniotomy',
                'name_ar' => 'فتح الجمجمة',
                'description' => 'Surgical opening of the skull to access the brain',
                'description_ar' => 'الفتح الجراحي للجمجمة للوصول إلى الدماغ',
                'category' => 'neurosurgery',
                'specialty' => 'neurosurgery',
                'complexity' => 'complex',
                'urgency_level' => 'urgent',
                'estimated_duration' => 300,
                'min_duration' => 240,
                'max_duration' => 480,
                'base_cost' => 60000.00,
                'surgeon_fee' => 25000.00,
                'anesthesia_fee' => 6000.00,
                'facility_fee' => 12000.00,
                'required_equipment' => ['microscope', 'neuro_monitors', 'drill'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'scrub_nurse', 'circulating_nurse'],
                'pre_operative_requirements' => ['mri', 'ct_scan', 'blood_work', 'consent', 'neuro_eval'],
                'post_operative_care' => ['icu_monitoring', 'neuro_checks', 'pain_management'],
                'requires_icu' => true,
                'requires_blood_bank' => true,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            
            // Ophthalmology
            [
                'code' => 'OP001',
                'name' => 'Cataract Surgery',
                'name_ar' => 'جراحة الساد',
                'description' => 'Surgical removal of cataract from the eye',
                'description_ar' => 'الإزالة الجراحية للساد من العين',
                'category' => 'ophthalmology',
                'specialty' => 'ophthalmology',
                'complexity' => 'minor',
                'urgency_level' => 'elective',
                'estimated_duration' => 30,
                'min_duration' => 20,
                'max_duration' => 45,
                'base_cost' => 3000.00,
                'surgeon_fee' => 1500.00,
                'anesthesia_fee' => 300.00,
                'facility_fee' => 500.00,
                'required_equipment' => ['phacoemulsification_machine', 'microscope', 'iol'],
                'required_team_roles' => ['primary_surgeon', 'scrub_nurse'],
                'pre_operative_requirements' => ['eye_exam', 'biometry', 'consent'],
                'post_operative_care' => ['eye_drops', 'follow_up'],
                'requires_icu' => false,
                'requires_blood_bank' => false,
                'requires_anesthesia' => false,
                'is_outpatient' => true,
                'is_active' => true,
            ],
            
            // ENT Surgery
            [
                'code' => 'ENT001',
                'name' => 'Tonsillectomy',
                'name_ar' => 'استئصال اللوزتين',
                'description' => 'Surgical removal of tonsils',
                'description_ar' => 'الاستئصال الجراحي للوزتين',
                'category' => 'ent',
                'specialty' => 'ent',
                'complexity' => 'moderate',
                'urgency_level' => 'elective',
                'estimated_duration' => 45,
                'min_duration' => 30,
                'max_duration' => 60,
                'base_cost' => 4000.00,
                'surgeon_fee' => 1800.00,
                'anesthesia_fee' => 600.00,
                'facility_fee' => 800.00,
                'required_equipment' => ['electrocautery', 'suction', 'mouth_gag'],
                'required_team_roles' => ['primary_surgeon', 'anesthesiologist', 'scrub_nurse'],
                'pre_operative_requirements' => ['blood_work', 'consent'],
                'post_operative_care' => ['pain_management', 'diet_modification', 'bleeding_watch'],
                'requires_icu' => false,
                'requires_blood_bank' => false,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            
            // Gynecology
            [
                'code' => 'GY001',
                'name' => 'Hysterectomy',
                'name_ar' => 'استئصال الرحم',
                'description' => 'Surgical removal of uterus',
                'description_ar' => 'الاستئصال الجراحي للرحم',
                'category' => 'gynecology',
                'specialty' => 'gynecology',
                'complexity' => 'major',
                'urgency_level' => 'elective',
                'estimated_duration' => 120,
                'min_duration' => 90,
                'max_duration' => 180,
                'base_cost' => 12000.00,
                'surgeon_fee' => 5000.00,
                'anesthesia_fee' => 1500.00,
                'facility_fee' => 2000.00,
                'required_equipment' => ['laparoscope', 'electrocautery', 'suction'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'scrub_nurse'],
                'pre_operative_requirements' => ['blood_work', 'imaging', 'consent', 'pap_smear'],
                'post_operative_care' => ['pain_management', 'wound_care', 'hormone_therapy'],
                'requires_icu' => false,
                'requires_blood_bank' => true,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            
            // Urology
            [
                'code' => 'UR001',
                'name' => 'Prostatectomy',
                'name_ar' => 'استئصال البروستاتا',
                'description' => 'Surgical removal of prostate gland',
                'description_ar' => 'الاستئصال الجراحي لغدة البروستاتا',
                'category' => 'urology',
                'specialty' => 'urology',
                'complexity' => 'major',
                'urgency_level' => 'elective',
                'estimated_duration' => 180,
                'min_duration' => 120,
                'max_duration' => 240,
                'base_cost' => 20000.00,
                'surgeon_fee' => 8000.00,
                'anesthesia_fee' => 2500.00,
                'facility_fee' => 3500.00,
                'required_equipment' => ['robotic_system', 'laparoscope', 'electrocautery'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'scrub_nurse', 'circulating_nurse'],
                'pre_operative_requirements' => ['blood_work', 'imaging', 'consent', 'cardiac_clearance'],
                'post_operative_care' => ['catheter_care', 'pain_management', 'wound_care'],
                'requires_icu' => false,
                'requires_blood_bank' => true,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
            
            // Emergency Procedures
            [
                'code' => 'EM001',
                'name' => 'Emergency Laparotomy',
                'name_ar' => 'فتح البطن الطارئ',
                'description' => 'Emergency surgical opening of the abdomen',
                'description_ar' => 'الفتح الجراحي الطارئ للبطن',
                'category' => 'emergency',
                'specialty' => 'general_surgery',
                'complexity' => 'major',
                'urgency_level' => 'emergency',
                'estimated_duration' => 120,
                'min_duration' => 60,
                'max_duration' => 300,
                'base_cost' => 15000.00,
                'surgeon_fee' => 6000.00,
                'anesthesia_fee' => 2000.00,
                'facility_fee' => 3000.00,
                'required_equipment' => ['electrocautery', 'suction', 'retractors'],
                'required_team_roles' => ['primary_surgeon', 'assistant_surgeon', 'anesthesiologist', 'scrub_nurse', 'circulating_nurse'],
                'pre_operative_requirements' => ['blood_work', 'imaging', 'consent'],
                'post_operative_care' => ['icu_monitoring', 'pain_management', 'wound_care'],
                'requires_icu' => true,
                'requires_blood_bank' => true,
                'requires_anesthesia' => true,
                'is_outpatient' => false,
                'is_active' => true,
            ],
        ];

        foreach ($procedures as $procedure) {
            SurgicalProcedure::create($procedure);
        }
    }
}